export const quests = {
    Exploration: [
      "Find a village",
      "Locate a desert temple",
      "Discover a jungle biome",
      "Travel to the Nether",
      "Locate a Stronghold",
      "Find a witch hut",
      "Explore an ocean monument",
      "Find a woodland mansion",
      "Explore a mineshaft",
      "Find an igloo with a basement",
      "Find a ruined portal",
      "Locate a pillager outpost",
      "Find a mushroom island",
      "Visit the End",
      "Discover all biomes",
      "Take a scenic boat ride",
      "Climb to the top of a mountain",
      "Explore a deep cave",
      "Find a fossil underground",
      "Discover a dripstone cave",
      "Locate a lush cave",
      "Explore a snow biome",
      "Visit the edge of the world",
      "Ride a strider in the Nether",
      "Locate a mangrove swamp",
      "Find a cherry grove biome",
      "Swim in a warm ocean",
      "Find a bastion remnant",
      "Explore the deep dark biome",
      "Visit a cold ocean ruins",
      "Find a coral reef",
      "Locate all types of villages",
      "Go on a 10,000 block journey",
      "Sail across a frozen ocean",
      "Explore the Nether roof (safely!)",
      "Discover an ancient city",
      "Find all wood types",
      "Use a spyglass in 3 biomes",
      "Map out your surroundings",
      "Climb a jungle tree",
      "Reach y=320 height",
      "Reach bedrock level",
      "Fly with elytra through a mountain",
      "Create a trail with torches",
      "Take a horse over 1,000 blocks",
      "Lead a camel through desert",
      "Ride a minecart through a cave",
      "Build a boat dock",
      "Travel only by boat for a day"
    ],
    Combat: [
      "Defeat 10 zombies",
      "Kill a creeper with a bow",
      "Take on a pillager outpost",
      "Defeat the Ender Dragon",
      "Fight a Ravager",
      "Win a raid",
      "Kill a wither skeleton",
      "Summon and defeat the Wither",
      "Defeat a blaze",
      "Fight 3 skeletons at once",
      "Survive a night without shelter",
      "PvP another player (friendly)",
      "Use a shield to block arrows",
      "Kill a phantom",
      "Take down a ghast with its own fireball",
      "Kill a hoglin",
      "Slay a guardian",
      "Survive the Nether for 10 minutes",
      "Fight mobs with only a wooden sword",
      "Use lava as a weapon",
      "Trap a mob using redstone",
      "Fight while riding a horse",
      "Win a fight using only snowballs",
      "Survive poison and win the battle",
      "Punch a creeper to death",
      "Knockback mobs into a pit",
      "Fight underwater with a trident",
      "Sneak attack a mob",
      "Set up a trap and trigger it on a mob",
      "Kill a mob with fall damage"
    ],
    Building: [
      "Build a treehouse",
      "Make a cozy cottage",
      "Construct a bridge across a river",
      "Build a lighthouse",
      "Make a statue",
      "Build a storage system",
      "Construct an animal pen",
      "Build a secret base",
      "Create a dock",
      "Make a castle wall",
      "Design a throne room",
      "Build a nether portal shrine",
      "Create a farm with all crops",
      "Build a fountain",
      "Construct a lookout tower",
      "Make a mine entrance",
      "Build a greenhouse",
      "Design a pixel art",
      "Create a village square",
      "Build a ship in a bottle",
      "Create a sky base",
      "Build a statue of your skin",
      "Make an aquarium",
      "Design a library",
      "Build an inn for travelers",
      "Create a jail for mobs",
      "Make a themed room",
      "Decorate a bedroom",
      "Build a tavern",
      "Construct a haunted house"
    ],
    Redstone: [
      "Build a working piston door",
      "Create a redstone lamp toggle",
      "Build an item sorter",
      "Make an automatic farm",
      "Design a hidden staircase",
      "Create a trap using dispensers",
      "Build an elevator",
      "Make a daylight sensor door",
      "Build a redstone timer",
      "Make a TNT cannon",
      "Build a music note doorbell",
      "Construct a redstone trapdoor",
      "Create a minecart launcher",
      "Make a working clock",
      "Build a piston trap",
      "Create a code-locked door",
      "Make a combination lock",
      "Design a redstone-powered drawbridge",
      "Build a 3x3 piston door",
      "Create a security alarm"
    ]
  };
  